### ISSUE TITLE
As Visitor, I would like to see in real time the ISS location

### ISSUE THREAD

**Issue by AntoineGGG** [WildCodeSchool/lyon-js-sept-2020-g4#10]
- [x] Add an img of the ISS station on the main page.

- [x] Create a div near the ISS to display her location.
- Using React Leaflet .js

**Comment by Rom-mtl** [comment]
Working on ISS component. Currently, I have an issue with the return of a "point" at the good Longitude/lattitude on the map (Cavans).
Canvas is define in pixel (400x600) but geoloc are define by Longitude and Lattitude... So I need to convert geolic into pixel..
